units:
  kx: cx
  ky: cy
  px: 2
  py: 2
points:
  key:
    padding: cy
    tags:
      1u: true
    footprints:
          choc_hotswap:
            type: choc
            nets:
              # from: P1
              # to: P2
              from: =colrow
              to: =column_net
            params:
              keycaps: true
              reverse: true
              hotswap: true
          diode:
            type: diode
            nets:
              from: =colrow
              to: =row_net
            anchor:
              shift: [0, -5]
          
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        outer:
          key:
            column_net: P20
        pinky:
          key:
            column_net: P19
        ring:
          stagger: 5
          key:
            column_net: P18
        middle:
          stagger: 5
          key:
            column_net: P15
        index:
          stagger: -6
          key:
            column_net: P14
        inner:
          stagger: -2
          key:
            column_net: P16
      rows:
        bottom:
          row_net: P7
        home:
          row_net: P6
        top:
          row_net: P5
        num:
          row_net: P4
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-20, -20]
      columns:
        near1:
          key:
            column_net: P20
        near2:
          key:
            column_net: P19
        home:
          rows:
            home:
              column_net: P18
            top:
              column_net: P15
              row_net: P3
          spread: 21.25
          rotate: -20
          origin: [-28, -2]
        far:
          key:
            column_net: P14
          spread: 21.25
          rotate: -15
          origin: [-11, -2]
      rows:
        home:
          row_net: P3
      
  rotate: -20
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [kx + px, ky + py]
        corner: px
        
    patch_outer:
      - type: polygon
        points:
          - ref: matrix_outer_num
            shift: [-13,20]
          - ref: matrix_outer_num
            shift: [132,20]
          - ref: thumbfan_home_top
            shift: [10,10]
          - ref: thumbfan_far_home
            shift: [10,20]
          - ref: thumbfan_far_home
            shift: [10,-10]
          - ref: thumbfan_near2_home
            shift: [7,-16]
          - ref: thumbfan_near1_home
            shift: [-11,-12]
          - ref: thumbfan_near1_home
            shift: [-11,4.5]
          - ref: matrix_outer_bottom
            shift: [-13,-14]
        
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false    
        tags: [1u]       
    keycap_outlines15:
      - type: keys
        side: left
        size: [1.5cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false    
        tags: [15u]       
    preview:
        main:
          type: outline
          name: patch_outer
        switches:
          type: outline
          name: keycap_outlines
          operation: subtract
pcbs:
  top_plate:
    outlines:
      edge:
        outline: preview # needs to change to be cuts not keycaps
        layer: Edge.Cuts
  board:
    outlines:
      edge:
        outline: patch_outer
        layer: Edge.Cuts
    footprints:
      mcu_l:
        type: promicro_pretty
        params:
          orientation: up
        anchor:
          ref:
            - matrix_inner_top
          shift: [20, -11]
          rotate: 270
      oled:
        type: oled
        anchor:
          ref:
            - matrix_inner_top
          shift: [15, -30]
          rotate: 90
        nets:
          CS: P1
          SCL: P2
          SDA: P0
      #mcu_r:
      #  type: promicro
      #  params:
      #    orientation: down
      #  anchor:
      #    ref:
      #      - matrix_inner_top
      #    shift: [22.5, -12.25]
      #    rotate: 270
      pad_plus:
        type: pad
        anchor:
          ref:
            - matrix_inner_top
          shift: [23, -6]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B+"
        nets:
          net: Bplus
      pad_minus:
        type: pad
        anchor:
          ref:
            - matrix_inner_top
          shift: [23, -3]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B-"
        nets:
          net: GND
      # trrs_l:
      #   type: trrs
      #   anchor:
      #     ref:
      #       - matrix_inner_bottom
      #     shift: [32, -15]
      #     rotate: 270
      #   params:
      #     reverse: false
      #     symmetric: false
      #   # The naming of the nets on this footprint is different from the Corne schematics.
      #   nets:
      #     A: ""
      #     B: VCC
      #     C: GND
      #     D: P0
      # trrs_r:
      #   type: trrs
      #   anchor:
      #     ref:
      #       - matrix_inner_bottom
      #     shift: [32, -13]
      #     rotate: 270
      #   params:
      #     reverse: true
      #     symmetric: false
      #   # The naming of the nets on this footprint is different from the Corne schematics.
      #   nets:
      #     A: ""
      #     B: VCC
      #     C: GND
      #     D: P0
      jumper_l:
        type: jumper
        anchor:
          ref:
            - matrix_inner_bottom
          shift: [23.5, 0]
          rotate: 270
        params:
          side: B
        nets:
          from: Bplus
          to: RAW
      jumper_r:
        type: jumper
        anchor:
          ref:
            - matrix_inner_bottom
          shift: [23.5, 0]
          rotate: 270
        params:
          side: F
        nets:
          from: Bplus
          to: RAW
      
      reset:
        type: button
        anchor:
          ref:
            - matrix_inner_bottom
          shift: [17, 0]
          rotate: 270
        params:
          variant: 2_pin_th
        nets:
          from: GND
          to: RST
#      info_l:
 #       type: text
  #      anchor:
   #       ref:
    #        - matrix_pinky_bottom
     #     shift: [0.75 kx, 0]
      #  params:
       #   text: "chocBoard"
     #     justify: left
     # info_r:
      #  type: text
       # anchor:
        #  ref:
         #   - matrix_pinky_bottom
        #  shift: [0.75 kx, 0]
       # params:
        #  layer: B.SilkS
         # text: "chocBoard"
          #justify: right mirror